# Question 1= add 1+2+3+..upto n Without using n(n+1)/2


num = int(input("Enter the no. upto which you want to have the summation"))
print(num)
result = 0
hold = num
# if is used here so that negative inputs can be avoided
if num <= 0:
    print("Enter a positive Integer number")
else:
    # Using while loop to do the addition
    while num > 0:
        result = result+num
        num = num-1
    print("Sum of the first", hold, "numbers is:", result)
